version: "3.7"

services:
  speech-azure:
    image: ikonoim/speech-azure:0.0.1
    build:
      context: speech-azure
      dockerfile: Dockerfile
      # runtime, or dev, or test for running tests
      target: runtime
    restart: unless-stopped
    ports:
      - 8181:8000
    environment:
      - AZURE_API_TOKEN
      - API_REGION
      - DEFAULT_LANG=es-MX
    volumes:
      - ./config.yaml:/etc/config.yaml
      - /etc/localtime:/etc/localtime
      - /var/lib/asterisk/sounds/:/sounds
      - ./speech-azure/src/:/app
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "10"
    networks:
     - voice-api

  # speech-google:
  #   image: ikonoim/speech-google:0.0.1
  #   build: 
  #     context: speech-google
  #     dockerfile: Dockerfile
  #     # runtime, or dev, or test for running tests
  #     target: runtime
  #   restart: unless-stopped
  #   ports:
  #     - 8182:8000
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS
  #   volumes:
  #     - /etc/localtime:/etc/localtime
  #     - /var/lib/asterisk/sounds/:/sounds
  #     ## - ./speech-google/src/:/app
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 20m
  #       max-file: "10"
  #   networks:
  #    - voice-api

  tts-azure:
    image: ikonoim/tts-azure:0.0.1
    build: 
      context: tts-azure
      dockerfile: Dockerfile
      # runtime, or dev, or test for running tests
      target: runtime
    restart: unless-stopped
    ports:
      - 8081:8000
    environment:
      - AZURE_API_TOKEN
    volumes:
      - ./config.yaml:/etc/config.yaml
      - /etc/localtime:/etc/localtime
      - /var/lib/asterisk/sounds/:/sounds
      ## - ./tts-azure/src/:/app
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "10"
    networks:
     - voice-api

networks:
  voice-api:
    name: voice-api
    # driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.31.128.0/24
